# Generated by Django 5.0.6 on 2024-06-26 11:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='search',
            field=models.CharField(default='', max_length=3000),
        ),
    ]
