# Generated by Django 4.2.13 on 2024-06-27 04:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_games_search'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='total_views',
            field=models.IntegerField(default=0),
        ),
    ]
