# Generated by Django 5.0.6 on 2024-06-27 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_games_total_views'),
    ]

    operations = [
        migrations.AddField(
            model_name='games',
            name='category',
            field=models.CharField(default='', max_length=200),
        ),
    ]
