# Generated by Django 5.0.6 on 2024-06-27 06:08

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_games_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='comments',
            fields=[
                ('comments_id', models.AutoField(primary_key=True, serialize=False)),
                ('comment', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('person', models.CharField(default='', max_length=200)),
                ('comment_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.games')),
            ],
        ),
    ]
