# Generated by Django 5.0.6 on 2024-06-27 08:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='replies',
            fields=[
                ('replies_id', models.AutoField(primary_key=True, serialize=False)),
                ('reply', models.TextField()),
                ('date', models.DateField(auto_now_add=True)),
                ('person', models.CharField(default='', max_length=200)),
                ('reply_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.comments')),
            ],
        ),
    ]
