# Generated by Django 5.0.6 on 2024-06-27 10:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_replies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comments',
            name='date',
            field=models.DateField(default=''),
        ),
        migrations.AlterField(
            model_name='replies',
            name='date',
            field=models.DateField(default=''),
        ),
    ]
