# Generated by Django 5.0.6 on 2024-06-27 12:25

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_alter_games_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='games',
            name='date',
            field=models.DateTimeField(verbose_name=datetime.datetime(2024, 6, 27, 12, 25, 49, 472920, tzinfo=datetime.timezone.utc)),
        ),
    ]
